package com.kunal.demo.rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Customer name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Date of birth")
   private java.util.Date dob;
   @org.kie.api.definition.type.Label("Total income")
   private long grossIncome;

   @org.kie.api.definition.type.Label(value = "Disposable income")
   private long disposableIncome;

   public Customer()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.util.Date getDob()
   {
      return this.dob;
   }

   public void setDob(java.util.Date dob)
   {
      this.dob = dob;
   }

   public String toString()
   {
      return "\tName: " + this.name + "\n\tdob: " + this.dob;
   }

   public long getGrossIncome()
   {
      return this.grossIncome;
   }

   public void setGrossIncome(long grossIncome)
   {
      this.grossIncome = grossIncome;
   }

   public long getDisposableIncome()
   {
      return this.disposableIncome;
   }

   public void setDisposableIncome(long disposableIncome)
   {
      this.disposableIncome = disposableIncome;
   }

   public Customer(java.lang.String name, java.util.Date dob, long grossIncome,
         long disposableIncome)
   {
      this.name = name;
      this.dob = dob;
      this.grossIncome = grossIncome;
      this.disposableIncome = disposableIncome;
   }
}